version: '3.9'
services:
  server:
    image: peaceiris/hugo:latest-mod
    command: 
      - server
      - --bind=0.0.0.0
      - --buildDrafts
    volumes:
      - ${PWD}:/src
    ports:
      - "1313:1313"